# Generated by Django 5.2.17 on 2026-09-28 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sgr_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Actividad')),
                ('execution_date', models.DateField(verbose_name='Fecha de Ejecución')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividad',
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('image_url', models.CharField(max_length=255, verbose_name='URL de Imagen/Archivo')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validado por Jefatura')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='operaciones.activity', verbose_name='Actividad Respaldada')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'db_table': 'evidencia',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Tarea')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('due_date', models.DateField(verbose_name='Fecha de Plazo')),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Completada', 'Completada')], default='Pendiente', max_length=50, verbose_name='Estado')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='sgr_core.institutionalgoal', verbose_name='Meta Institucional')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'tarea_agenda',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='operaciones.task', verbose_name='Tarea de Agenda'),
        ),
    ]
