# Generated by Django 5.2.17 on 2026-09-15 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0001_initial'),
        ('sgr_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_usuario_atendido', models.CharField(max_length=12, verbose_name='RUT Vecino Atendido')),
                ('nombre_usuario_atendido', models.CharField(max_length=100, verbose_name='Nombre Vecino Atendido')),
                ('tipo_gestion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Gestión')),
                ('resultado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Resultado / Resolución')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Atención')),
            ],
            options={
                'verbose_name': 'Atención Social',
                'verbose_name_plural': 'Atenciones Sociales',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Actividad')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('Ingresado', 'Ingresado'), ('En proceso', 'En proceso'), ('Realizado', 'Realizado'), ('Suspendido', 'Suspendido')], default='Ingresado', max_length=30)),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha Límite')),
                ('accion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Acción a Realizar')),
                ('contacto_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Contacto')),
                ('contacto_fono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Contacto')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='actividades', to='rrhh.funcionario')),
                ('item_medicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='sgr_core.itemmedicion')),
                ('atencion_social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='operaciones.atencionsocial')),
            ],
            options={
                'verbose_name': 'Actividad Operativa',
                'verbose_name_plural': 'Actividades Operativas',
            },
        ),
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título del Compromiso')),
                ('estado', models.CharField(choices=[('Ingresado', 'Ingresado'), ('En curso', 'En curso'), ('Finalizado', 'Finalizado'), ('Postergado', 'Postergado')], default='Ingresado', max_length=30)),
                ('solicitante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Solicitante / Junta Vecinal')),
                ('territorio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Territorio / Sector')),
                ('area_apoyo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área de Apoyo')),
                ('fecha_limite', models.DateField(verbose_name='Fecha Límite')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='compromisos', to='rrhh.funcionario')),
                ('meta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromisos', to='sgr_core.metainstitucional')),
            ],
            options={
                'verbose_name': 'Compromiso Territorial',
                'verbose_name_plural': 'Agenda de Compromisos',
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.CharField(max_length=50, unique=True, verbose_name='Código Único (Ej: EV-0412)')),
                ('imagen_url', models.CharField(max_length=255, verbose_name='URL Fotografía')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('estado_validacion', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Observada', 'Observada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=30)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Validación')),
                ('motivo_rechazo', models.TextField(blank=True, null=True, verbose_name='Motivo de Rechazo / Observación')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='operaciones.actividad')),
                ('verificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_verificadas', to='rrhh.funcionario')),
            ],
            options={
                'verbose_name': 'Evidencia Fotográfica',
                'verbose_name_plural': 'Evidencias Fotográficas',
            },
        ),
    ]
