# Generated by Django 5.2.17 on 2026-10-03 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
        ('sgr_core', '0002_delegation_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección'),
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('benefit_type', models.CharField(choices=[('food_basket', 'Canasta de alimentos'), ('school_kit', 'Kit escolar'), ('medical_aid', 'Ayuda médica'), ('other', 'Otro')], max_length=30, verbose_name='Tipo de Beneficio')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('delivered', models.BooleanField(default=False, verbose_name='Entregado')),
                ('delivery_area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='delivered_benefits', to='sgr_core.delegation', verbose_name='Delegación de Entrega')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='operaciones.employee', verbose_name='Funcionario Beneficiario')),
            ],
            options={
                'verbose_name': 'Beneficio',
                'verbose_name_plural': 'Beneficios',
                'db_table': 'beneficio',
            },
        ),
        migrations.CreateModel(
            name='TaskReassignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('reason', models.CharField(choices=[('vacation', 'Vacaciones'), ('absence', 'Ausencia'), ('other', 'Otro')], max_length=20, verbose_name='Motivo de la Derivación')),
                ('reassigned_at', models.DateTimeField(verbose_name='Fecha de Derivación')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('original_employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='original_reassignments', to='operaciones.employee', verbose_name='Funcionario Original')),
                ('reassigned_employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='received_reassignments', to='operaciones.employee', verbose_name='Funcionario Receptor')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignments', to='operaciones.task', verbose_name='Tarea Derivada')),
            ],
            options={
                'verbose_name': 'Derivación de tarea',
                'verbose_name_plural': 'Derivaciones de tareas',
                'db_table': 'derivacion_tarea',
            },
        ),
    ]
