# Generated by Django 5.2.17 on 2026-10-07 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_employee_address_benefit_taskreassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('jefatura', 'Jefatura'), ('usuario', 'Usuario')], default='usuario', max_length=20, verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='operaciones.employee', verbose_name='Responsable asignado'),
        ),
    ]
