# Generated by Django 5.2.17 on 2026-09-28 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de Delegación')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Delegación',
                'verbose_name_plural': 'Delegaciones',
                'db_table': 'delegacion',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre del Período')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha Fin')),
                ('quarter', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], verbose_name='Trimestre')),
                ('status', models.CharField(choices=[('En curso', 'En curso'), ('Cerrado', 'Cerrado')], default='En curso', max_length=15, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Período de Medición',
                'verbose_name_plural': 'Períodos de Medición',
                'db_table': 'periodo',
            },
        ),
        migrations.CreateModel(
            name='InstitutionalGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=100, verbose_name='Meta Institucional')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ponderación (%)')),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='goals', to='sgr_core.delegation', verbose_name='Delegación')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='goals', to='sgr_core.period', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Meta Institucional',
                'verbose_name_plural': 'Metas Institucionales',
                'db_table': 'meta',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Porcentaje Cumplido (%)')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='sgr_core.institutionalgoal', verbose_name='Meta')),
            ],
            options={
                'verbose_name': 'Registro de Cumplimiento',
                'verbose_name_plural': 'Registros de Cumplimiento',
                'db_table': 'cumplimiento',
            },
        ),
        migrations.CreateModel(
            name='MeasurementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=100, verbose_name='Indicador / Item de Medición')),
                ('unit_of_measure', models.CharField(max_length=50, verbose_name='Unidad de Medida')),
                ('baseline', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Línea Base')),
                ('target_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Objetivo')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_items', to='sgr_core.institutionalgoal', verbose_name='Meta')),
            ],
            options={
                'verbose_name': 'Ítem de Medición',
                'verbose_name_plural': 'Ítems de Medición',
                'db_table': 'item_medicion',
            },
        ),
    ]
