# Generated by Django 5.2.17 on 2026-09-15 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del Período')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('trimestre', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], verbose_name='Trimestre')),
                ('dias_computables', models.IntegerField(default=60, verbose_name='Días Hábiles Computables')),
                ('estado', models.CharField(choices=[('En curso', 'En curso'), ('Cerrado', 'Cerrado')], default='En curso', max_length=15)),
            ],
            options={
                'verbose_name': 'Período de Medición',
                'verbose_name_plural': 'Períodos de Medición',
            },
        ),
        migrations.CreateModel(
            name='MetaInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Meta Institucional')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('ponderacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ponderación (%)')),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='metas', to='rrhh.delegacion')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='metas', to='sgr_core.periodo')),
            ],
            options={
                'verbose_name': 'Meta Institucional',
                'verbose_name_plural': 'Metas Institucionales',
            },
        ),
        migrations.CreateModel(
            name='ItemMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Indicador / Item de Medición')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Operación')),
                ('unidad_medida', models.CharField(max_length=50, verbose_name='Unidad de Medida')),
                ('linea_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Línea Base')),
                ('valor_objetivo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Objetivo')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_medicion', to='sgr_core.metainstitucional')),
            ],
            options={
                'verbose_name': 'Ítem de Medición',
                'verbose_name_plural': 'Ítems de Medición',
            },
        ),
        migrations.CreateModel(
            name='Cumplimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Porcentaje Cumplido (%)')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cálculo')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cumplimientos', to='sgr_core.metainstitucional')),
            ],
            options={
                'verbose_name': 'Registro de Cumplimiento',
                'verbose_name_plural': 'Registros de Cumplimiento',
            },
        ),
    ]
