# Generated by Django 5.2.17 on 2026-10-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgr_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegation',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Código hex, ej: #E63946', max_length=7, verbose_name='Color distintivo'),
        ),
    ]
